config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :update, :edit, :distroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurants = Restaurant.find(params[:restaurant_id])
    @reviews = Review.new
  end
  def create
    @restaurants = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

private

def review_params
  params.require(:review).permit(:rating, :content)

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |r| %>

<%= r.input :name, label: 'Restaurant name',error: 'Name is mandatory, please specify one' %>

<%= r.input :address, error: 'Adress is mandatory, please specify one' %>
<%= r.input :category,label: 'Categories: cinese, italian, japanese, french, belgian' ,error: 'Category is mandatory, please specify one' %>
<%= r.input :phone_number %>
<%= r.button :submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h2>Edit Restaurant</h2>
<%= render 'form', restaurant: @restaurant %>
<%= link_to "Back to List", restaurants_path %>

app/views/restaurants/index.html.erb
<h2>Restrurants</h2>
<ul>
  <% @restaurants.each do |restaurant| %>
  <li><%= restaurant.name %>
  <%= link_to "Details",restaurant_path(restaurant)  %> </li>
</ul>

  <% end %>
  <br><br>
  <%= link_to "+ Add Restaurant", new_restaurant_path%>

app/views/restaurants/new.html.erb
<h2>Add Restaurant</h2>
<%= render 'form', restaurant: @restaurant %>
<%= link_to "Back to List", restaurants_path %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<h3>Reviews </h3>
<p><% @restaurant.reviews.each do |review|%>
  <ul>
  <li> <%= review.content %>
<p>Rating <%= review.rating %></p></li>
  </ul>
  <% end %>
</p>
<%= link_to "Back to list", restaurants_path %>
<%= link_to "Edit Restaurant details", edit_restaurant_path, class:"btn btn-primary" %>
<%= link_to "Add a Review", new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurants, @reviews] do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit  %>
<% end %>
<%= link_to "Back Restaurant list", restaurants_path  %>